name: CI

on:
  push:
    #branches: [ master ]
  pull_request:
    #branches: [ master ]


jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.2.0
        
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
      
      - name: Restore Packages
        run: nuget restore de.hykario.valorantlogin.sln
      
      - name: Build solution
        run: msbuild de.hykario.valorantlogin.sln -t:build -property:Configuration=Release
